### PR TITLE
use strike-through for deprecated model attribute/operation/children …

### PR DESCRIPTION
**Pull request by rhusar**
…names

### CODE REVIEW

**Comment by rhusar** [comment]
BTW What do people think about pretty printing HTML so this repo does not have to change everything for every update?

**Comment by ctomc** [comment]
wdym about pretty printing HTML? not using minify?

**Comment by rhusar** [comment]
Yeah, I mean not using anything to 'minify' the HTML and rather pretty print so changes to this repo don't have to change the whole content every time. Makes changes to the content easier to see and manage, but makes the pages bit larger.

**Comment by ctomc** [comment]
pages are huge without it, that is main reason.
Optimal solution would be to have some kind of static "template" html and load the page model via JSON request and do rendering via JS.
that way we wouldn't have htmls pre-generated which would really reduce size.

**Comment by rhusar** [comment]
I see, the size per distribution could be be up to 20 MB. Using JS+JSON would reduce the distribution size to minimum.

**Pull request merged**
